name: openACC Build

on:
  push:
    branches: [ openACC ]
  pull_request:
    branches: [ openACC ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: make
      run: cd src && make openACC

