name: OMPGen

on:
  push:
    branches: [ WorkingBranch ]
  pull_request:
    branches: [ WorkingBranch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: make
      run: cd src && make
      
    - name: list files
      run: ls -al
      
    - name: Generate
      run:  ./StarPlat -s -f ../graphcode/sssp_dslV2 -b omp
      

