name: CUDAGen

on:
  push:
    branches: [ WorkingBranch ]
  pull_request:
    branches: [ WorkingBranch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: make
      run: cd src && make
      
    - name: list files
      run: ls -al
      
      
      # CUDA Generation
    - name: Generate CUDA
      run:  ./src/StarPlat -s -f ./graphcode/sssp_dslV2 -b cuda
      

